version: '3'
services:

  app_flask_for_prometheus:
    build:
      context: ./API_Flask_for_prometheus
      dockerfile: Dockerfile
    ports: 
      - 5000:5000
    depends_on:
      - prometheus
    container_name: app_flask_for_prometheus
    networks:
      scrapper:

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      -  prometheus_logs:/prometheus
    networks:
      scrapper:

  scrapper:
    build:
      context: ./scrappers
      dockerfile: Dockerfile
    container_name: scrapper
    command : [ "python", "crawling_async.py", "mongodb", "0" , "--crawling_robots=0"]
    networks:
      scrapper:
  
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - 3000:3000
    volumes:
      - grafana-data:/var/lib/grafana   
    networks:
      scrapper:

  mongodb:
    image: mongo
    container_name: mongo
    ports:
      - 27017:27017
    volumes:
      - MongoDB_scrapping_volume_v2:/data/db
    networks:
      scrapper:
  
networks:
  scrapper:

volumes:
  MongoDB_scrapping_volume_v2:
    external: true
  prometheus_logs:
    external: true
  grafana-data:
    external: true