version: '3'
services:

  app_flask_for_prometheus:
    build:
      context: ./API_Flask_for_prometheus
      dockerfile: Dockerfile
    depends_on:
      - prometheus
    container_name: app_flask_for_prometheus
    networks:
      scrapper:

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      -  ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      -  prometheus-data:/prometheus
    networks:
      scrapper:


  scrapper:
    build:
      context: ./scrappers
      dockerfile: Dockerfile
    container_name: scrapper
    command : [ "python", "crawling_async.py", "mongodb", "0" , "--crawling_robots=0"]
    networks:
      scrapper:
      
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - 3000:3000
    volumes:
      - grafana-data:/var/lib/grafana   
      - ./grafana/dashboards/:/var/lib/grafana/dashboards/
    networks:
      scrapper:

  mongodb:
    image: mongo
    container_name: mongo
    volumes:
      - mongodb-data:/data/db
      -  ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      scrapper:
  
networks:
  scrapper:

volumes:
  mongodb-data:
    driver: local
  prometheus-data:
    driver: local
  grafana-data:
    driver: local