{
 "title": "Monitoring scrapper",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Nombre de pages html",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "expr": "nb_html_pages", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Nb sitemaps",
   "type": "stat",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nb_sitemaps_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Pourcentage de requêtes réussies",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 7, "x": 10, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "prct_requetes_reussies", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Pourcentage de sitemaps scrappés",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "prct_liens_scrappes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Nombre de requêtes",
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nb_requetes", "legendFormat": "__auto" }
   ]
  }
 ]
}